"""
fhir_consumer_bert.py
---------------------
Multi-label data preparation layer for the PubMedBERT backend (Experiment A).

Re-uses fetch_training_examples() from fhir_consumer and adds:
  - build_label_index(): builds the ICD-10 label vocabulary from the corpus.
  - prepare_bert_examples(): prepares (clinical_text, label_vector) ready for the dataset.

The vocabulary can be built locally (from the silo's own admissions) or loaded
from a JSON generated by mimic_builder (for consistency across silos).
"""

from __future__ import annotations

import json
import logging
import os
from collections import Counter
from pathlib import Path
from typing import Any

from ai_client.fhir_consumer import TrainingExample, fetch_training_examples

log = logging.getLogger(__name__)

# Optional path to the label vocabulary pre-built by mimic_builder.
# If it exists, it is preferred over local construction to ensure consistency
# in label indices across all federated silos.
_LABEL_INDEX_PATH = os.getenv("BERT_LABEL_INDEX_PATH", "")


def build_label_index(
    examples: list[TrainingExample],
    benchmark: str = "full",
    label_index_path: str = _LABEL_INDEX_PATH,
) -> dict[str, int]:
    """
    Builds or loads the ICD-10 label vocabulary.

    Preference order:
      1. Load from `label_index_path` if the file exists (consistency across silos).
      2. Build locally from examples, filtered by `benchmark`.

    Args:
        examples:         TrainingExamples with all_icd10_codes populated.
        benchmark:        "top50" → 50 most frequent codes;
                          "full"  → all codes with ≥10 occurrences;
                          "none"  → all codes present.
        label_index_path: Path to a pre-built vocabulary JSON.

    Returns:
        Dictionary {ICD10_code: int_index}, sorted by descending frequency.
    """
    if label_index_path and Path(label_index_path).exists():
        with open(label_index_path, encoding="utf-8") as f:
            index = json.load(f)
        log.info("Label index loaded from %s: %d labels.", label_index_path, len(index))
        return index

    log.info("Building label index locally (benchmark=%s)...", benchmark)
    counter: Counter[str] = Counter()
    for ex in examples:
        codes = ex.all_icd10_codes if ex.all_icd10_codes else [ex.icd10_code]
        for code in codes:
            if code:
                counter[code.upper()] += 1

    if benchmark == "top50":
        selected = [code for code, _ in counter.most_common(50)]
    elif benchmark == "full":
        selected = [code for code, cnt in counter.most_common() if cnt >= 10]
    else:
        selected = [code for code, _ in counter.most_common()]

    label_index = {code: idx for idx, code in enumerate(selected)}
    log.info("Label index built: %d labels.", len(label_index))
    return label_index


def save_label_index(label_index: dict[str, int], path: str) -> None:
    """Saves the label index to JSON for sharing across silos."""
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(label_index, f, indent=2)
    log.info("Label index saved to %s (%d labels).", path, len(label_index))


def fetch_bert_training_data(
    fhir_url: str,
    partition_id: int = -1,
    benchmark: str = "full",
    max_examples: int = 0,
    seed: int = 42,
) -> tuple[list[TrainingExample], dict[str, int]]:
    """
    Fetches FHIR examples and prepares the label index for the BERT backend.

    Args:
        fhir_url:      Base URL of the HAPI FHIR server.
        partition_id:  Non-IID partition to consume (-1 = all).
        benchmark:     Benchmark filter for the label index.
        max_examples:  Limits the number of examples (0 = no limit).
        seed:          Seed for shuffling when limiting examples.

    Returns:
        (examples, label_index) where label_index is the ICD-10 vocabulary.
    """
    import random as _random
    examples, stats = fetch_training_examples(fhir_url)

    if stats.warnings:
        for w in stats.warnings:
            log.warning("FHIR consumer: %s", w)

    if partition_id >= 0:
        tag = f"partition_id={partition_id}"
        examples = [ex for ex in examples if tag in ex.partition_note or not ex.partition_note]
        log.info("Partition %d: %d examples.", partition_id, len(examples))

    if max_examples > 0 and len(examples) > max_examples:
        _random.seed(seed + max(partition_id, 0))
        _random.shuffle(examples)
        examples = examples[:max_examples]
        log.info("Limited to %d examples.", max_examples)

    label_index = build_label_index(examples, benchmark=benchmark)
    return examples, label_index
